modLoader = "javafml"
loaderVersion = "[40,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "kubejsdebugadapter"
version = "${version}"
displayName = "KubeJS Debug Adapter"
authors = "WarmthDawn"
description = '''
A mod adding a debug adapter protocol for KubeJS.
'''
#logoFile = ""

[[dependencies.kubejsdebugadapter]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.kubejsdebugadapter]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.kubejsdebugadapter]]
modId = "architectury"
mandatory = true
versionRange = "[4.5.76,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.kubejsdebugadapter]]
modId = "rhino"
mandatory = true
versionRange = "[1802.1.13,)"
ordering = "AFTER"
side = "BOTH"


[[dependencies.kubejsdebugadapter]]
modId = "kubejs"
mandatory = true
versionRange = "[1802.5.3,)"
ordering = "AFTER"
side = "BOTH"

